### ISSUE TITLE
Get incorrect ArrayBuffer when decode apng or gif

### ISSUE THREAD

**Issue by xinxixingchen** [yegor-pelykh/image-in-browser#4]
I want to draw each frame of apng or gif through canvas, the code is as follows:
```
const reader = decodeImage({
  data: arraybuffer,
})
const frame = reader.getFrame(index);
const imgData = ctx.getImageData(0, 0, canvasWidth, canvasHeight);
imgData.data.set(frame.getBytes({
  order: 0,
}));
ctx.putImageData(imgData, 0, 0);
```
But the drawing is not the correct picture, as shown below(The right side is drawn by canvas): 
![result](https://github.com/yegor-pelykh/image-in-browser/assets/19337982/aa6a51f1-c20f-4e3d-a31f-5d812cf25267)

**I want to know how to get the complete picture of the each frame**

**Comment by yegor-pelykh** [comment]
Hi @xinxixingchen,
This was the bug.
Now it is fixed by 79f22e0.
Released v2.4.1.
