### ISSUE TITLE
support SkipExif as option when convert call encodeImage..

### ISSUE THREAD

**Issue by gowy222** [yegor-pelykh/image-in-browser#6]
pls.. SkipExif needed

**Comment by yegor-pelykh** [comment]
Hi @gowy222. Please try the new version [`v3.1.0`](https://github.com/yegor-pelykh/image-in-browser/releases/tag/v3.1.0).
It seems I've done what you need.

Now there is an additional option `skipExif` for the following functions:
- `encodeImageByMimeType()`
- `encodeNamedImage()`
- `encodeJpg()`
- `encodeTiff()`
- `encode()` methods of the corresponding encoders

I've also added an example of using this option in a separate example repository:
[remove-exif-data.ts](https://github.com/yegor-pelykh/image-in-browser.examples/blob/main/examples/exif-data/remove-exif-data.ts)

Please give me your feedback to see if I can close this issue.
